export const DWELLINGS_ROUTE = '/dwellings'
export const DWELLING_ROUTE = '/dwelling'
export const USER_ROUTE = '/user'
export const OWNER_ROUTE = '/owner'
export const ADMIN_ROUTE = '/admin'
export const NOT_FOUND_ROUTE = '/404'
